enum ActionType {
  POPULAR = "FETCH_POPULAR_MOVIES",
  TOP_RATED = "FETCH_TOP_RATED_MOVIES",
  UPCOMING = "FETCH_UPCOMING_MOVIE",
  RECENTLY_VIEWED = "ADD_RECENTLY_VIEWED_MOVIE",
}

export default ActionType;
